name: Deploy to Shared Hosting via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify the Node.js version you need
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build # Adjust this command if your build script is different

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: meghna.satisfyhost.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home/liservic/imran/ # Replace with your target directory
          local-dir: ./dist # Directory of your project (adjust if needed)
          port: 21
