name: Deploy to Shared Hosting via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: meghna.satisfyhost.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home/liservic/imran/ # Replace with your target directory
          local-dir: ./ # Directory of your project (adjust if needed)
          port: 21
